### PR TITLE
Use the correct local path in the help window

### PR DESCRIPTION
**Pull request by shun2wang**
fixed https://github.com/jasp-stats/jasp-issues/issues/1772

### CODE REVIEW

**Comment by JorisGoosen** [comment]
The changes look fine, but why did you mark it as a draft?

**Comment by shun2wang** [comment]
Ah, looks like this fix just make .gif show in web, in fact the path of ,gifreference to  `JASP/Resources/Help/gif/interaction_effect_anova.gif `instead of `jaspAnova\help\gif\interaction_effect_anova.gif `

**Comment by JorisGoosen** [comment]
Aaah yeah that is right. The local path isnt set correctly inside the helpwindow.

You can do it like this: ``

I'll see and make sure this is added to some doc somewhere if it isnt yet.

**Comment by JorisGoosen** [comment]
So turns out it was already there: https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/development/jasp-adding-module.md#help but I can understand how someone could miss it (as Ive forgotten about it and am the one who implemented it :p)

**Comment by shun2wang** [comment]
haha yeah i forgot it too. I'll be back soon.
Thank you Joris!

**Comment by shun2wang** [comment]
@JorisGoosen this can be merged into 0.16.4, right? ^_^

**Review by JorisGoosen — APPROVED** [review]

**Comment by JorisGoosen** [comment]
Yeah for sure!

I just totally forgot to look at this again...
I wanted to test it first, but I dont have time anymore and it looks pretty good so lets merge it and hope I don't make @JohnnyDoorn @Kucharssim  or @vandenman unhappy ;)

**Pull request merged**
