### PR TITLE
R4 upgrade

### PR DESCRIPTION
**Pull request by vandenman**
No changes to the code were necessary

edit: I spoke too soon

edit2: the tests failed locally but seem to pass here so...

edit3: so 2 tests consistently fail for me locally, but if that doesn't happen on the CI then I don't mind.

### CODE REVIEW

**Comment by TimKDJ** [comment]
Could you rebase this branch to ensure the tests from https://github.com/jasp-stats/jaspAnova/commit/60750cd260fd94543595c629a5e5515c72d6a0e6 also pass on R4?

**Comment by vandenman** [comment]
downloading https://cloud.r-project.org/bin/windows/contrib/4.0/vctrs_0.3.8.zip fails, I'll retrigger the tests once that url works again.

**Comment by vandenman** [comment]
@TimKDJ it looks like jaspTools failed on windows... have you seen this error before?

**Comment by vandenman** [comment]
@TimKDJ just re-running the checks 3 times makes them pass :D

**Comment by TimKDJ** [comment]
Yeah you were right about the absence of `vctrs`.
Did something fail other than the installation of that package?

**Comment by vandenman** [comment]
yes, jaspTools just errored for some weird reason, but I think the old logs disappeared. It failed to fetch jasp-desktop I think.

**Review by TimKDJ — APPROVED** [review]
Mkay... let's hope it was a one time deal.

**Pull request merged**
