### PR TITLE
Delete emmeans environment anyway

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/jaspAnova/issues/14

I left a comment to ensures that we don't forget why this is there.

### CODE REVIEW

**Comment by AlexanderLyNL** [comment]
I tried to run this on 0.14.1 developer module but got an error message: 

Screenshot 2021-02-18 at 19 50 31

I'll try later

**Comment by vandenman** [comment]
@AlexanderLyNL do you have time to look at this or shall I reassign this? :)

**Comment by AlexanderLyNL** [comment]
I'll have a look in a bit

**Comment by AlexanderLyNL** [comment]
I forgot what this is about exactly. Perhaps ask someone else.

**Pull request merged**
