### PR TITLE
Fix ordinal restrictions issues

### PR DESCRIPTION
**Pull request by Kucharssim**
fixes https://github.com/jasp-stats/jasp-test-release/issues/1716 (should address point 2)

fixes https://github.com/jasp-stats/jasp-test-release/issues/1757

### CODE REVIEW

**Review by juliuspf — COMMENTED** [review]
Looks good. I also cannot seem to reproduce the error from before anymore. However, I found another bug (maybe). Would you rather merge this now and address that in a different PR or within this PR. It should be a small fix.

**Review by juliuspf — CHANGES_REQUESTED** [review]
I might be mistaken, but could it be that you only fixed ANCOVA and repeated measures ANOVA?

**Comment by Kucharssim** [comment]
> I might be mistaken, but could it be that you only fixed ANCOVA and repeated measures ANOVA?

The functions for ANCOVA are used for ANOVA, so fixing the ANCOVA should also fix the ANOVA. Did the issue persist for you?

**Comment by juliuspf** [comment]
yes it does persist

**Comment by Kucharssim** [comment]
No, it is fixed for me... 

Hm, when I checked it with the latest nightly, it is not fixed as well, but if I change the name of the module in `DESCRIPTION` and `Description.qml` (so that it's installed as a "new" module instead replacing the ANOVA module), it is fixed. So perhaps installing the dev. module did not work?

**Comment by juliuspf** [comment]
yes I think that must be it. I was having trouble with that before in this round of testing.

**Comment by Kucharssim** [comment]
Hm so I checked again and I do think it's fixed. However, jasp-stats/jasp-test-release#1716 is still not fixed. Not sure why, need to look into it again.

**Comment by juliuspf** [comment]
you mean part 1) or 2)?

**Comment by Kucharssim** [comment]
Part 2). I did not do anything about 1) right now, because it will be fixed in https://github.com/jasp-stats/INTERNAL-jasp/issues/1647, but that is not ready for this release.

**Comment by juliuspf** [comment]
yes. I see the second issue still as well.

**Comment by Kucharssim** [comment]
good idea, thanks

**Comment by juliuspf** [comment]
I can't really check this because installing the dev module doesnt work. It errors when I change the name in the two description files.

**Review by vandenman — APPROVED** [review]
I can replicate both https://github.com/jasp-stats/jasp-test-release/issues/1716 and https://github.com/jasp-stats/jasp-test-release/issues/1757 in development and they appear fixed by this PR.

**Pull request merged**
