### PR TITLE
 dont make referenceGrid on error 

### PR DESCRIPTION
**Pull request by JohnnyDoorn**

### CODE REVIEW

**Comment by TimKDJ** [comment]
Is this based on a commit to jasp-desktop? If so could you specify which.
And it appears to have a merge conflict now...

**Comment by JohnnyDoorn** [comment]
Hmm I don't see the conflict.. 
it's https://github.com/jasp-stats/jasp-desktop/pull/4295

also just added the extra commit in that PR

**Comment by TimKDJ** [comment]
If you try to rebase your branch you should run into it

**Comment by JohnnyDoorn** [comment]
ah ok.. well I can also remove these changes and add them later again, they're supertiny

**Pull request merged**
