### PR TITLE
Updates to BANOVAs: random effects in RM-BANOVA, optional marginality, and more flexibility in priors

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1550

The checkbox `Legacy results` reverts the RM-BANOVA results to what they were before this PR.

In addition:

- The principle of marginality can now be violated.
- The prior on the model space can be set to something other than uniform. There are the same options as in Bayesian linear regression and a custom option which is essentially a Bernoulli prior but where the prior inclusion probability of each term can be specified individually.
- The r-scale can now be specified individually for fixed and random factors. The old option is the default, where users specify 3 r-scales, one for factors, one for covariates, and one for random factors. For some reason, BayesFactor does not allow individual r-scales for covariates so that isn't possible.
- The QML files of the Bayesian ANOVAs now reuse common QML elements.

@boutinb I added you as a reviewer for two specific questions.
1. I've heavily reorganized the QML files, but I did not change many labels/ `qsTr()`s. Should I change things in the PO files to ease the translations?
2. I added a QML enum in inst/qml/common/AnalysisType.qml. I haven't seen this before in Jasp so please let me know if there is a better way to do that.

Before this is merged I still need to update the help files. However, all R functionality should already work, so I figured I'd open the PR already and not miss any deadlines.

### CODE REVIEW

**Review by Kucharssim — COMMENTED** [review]
The code looks good to me, the changes are reasonable. 

I just tested it in R and it looks like it does what it supposed to do, but I have not tried to break it in JASP. Will do that later today/tomorrow

One general observation I have is that it would be nice for the sake of code style consistency is to use `.banova` instead of `.BANOVA` prefix to function names, but that we can (should) do in a separate PR.

Another suggestion is whether we want to be more verbose in alerting users in case they read a .jasp file made with an earlier version of JASP. Something like this: https://github.com/jasp-stats/jaspSem/pull/46 but explaining the difference between the old and new behavior of the analysis. Seems like this change is big enough to warrant warning the users explicitly.

**Comment by vandenman** [comment]
> One general observation I have is that it would be nice for the sake of code style consistency is to use .banova instead of .BANOVA prefix to function names, but that we can (should) do in a separate PR.

Yes, definitely. The `.BANOVA` prefix predates the modules split-off and it would be nice to get rid of it (things are unreasonable verbose now).

> Something like this: https://github.com/jasp-stats/jaspSem/pull/46

That sounds like a good idea! I'll take a look at that soon, it might be nice if we can refer to a preprint because I don't know if I can write it up in less than a paragraph.

**Review by Kucharssim — APPROVED** [review]
I just played around with the analysis in JASP, looks like it's working fine.

Whether you want to add the upgrade note to this PR or whether you want to make a separate PR, I'll leave to your discretion.

**Comment by vandenman** [comment]
Let's not make this PR any bigger than it already is, I've created https://github.com/jasp-stats/INTERNAL-jasp/issues/1829 for both comments.

**Pull request merged**
