### PR TITLE
Raincloudplot: do not use JaspColumn_.dependent._Encoded as title

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1757

This PR changes the behavior in 2 ways.

1. The title of the jaspPlot is "Dependent" if the y-axis title equals `""`, otherwise it matches the y-axis title.
2. If the y-axis title equals empty whitespace, then we set it to NULL which removes the space in the plot for the title.

Before:
image

After:
image

You can see the 2nd point in effect in the test files, but also in that in the screenshot after the y-axis tick labels line up with the title of the jaspPlot ("Dependent").

@koenderks do you have time to review this?

### CODE REVIEW

**Comment by vandenman** [comment]
@Kucharssim since @koenderks probably doesn't have time, do you have time to review this?

**Review by Kucharssim — APPROVED** [review]
So the code looks ok, it seems to work fine.

I encountered an error though when displaying the plot:

Screenshot 2022-09-06 at 12 03 04

See the attached .jasp file:
[debug.jasp.zip](https://github.com/jasp-stats/jaspAnova/files/9495602/debug.jasp.zip)

After changing the font `default: Lucida Grande`-> `.SF NS Mono` and refreshing the analysis, I first got the `Polygon edge not found` error that we encountered some time before, after switching back to Lucida Grande and refreshing again it started working. 

I think this is unrelated to the current PR, if that's the case, it's ok to merge this. Not sure whether the error I saw deserves a new issue?

**Comment by vandenman** [comment]
I think it's unrelated but I will check if I can replicate it before merging.

**Comment by vandenman** [comment]
So I installed `SF Mono` as a font but I cannot replicate the error... I'm afraid it's mac specific. Does this error also occur without this PR? If yes, then perhaps it's better to make an issue and then merge this.

**Comment by Kucharssim** [comment]
> Does this error also occur without this PR?

It doesn't. But I just tried to test this branch again and it did not happen anymore, so who knows what happened

**Comment by boutinb** [comment]
So we can merge this PR?

**Pull request merged**
