### PR TITLE
Use multivariate as default for follow-up tests RM ANOVA

### PR DESCRIPTION
**Pull request by JohnnyDoorn**
While setting this to "false" is in line with SPSS, the multivariate option is generally considered to be more appropriate since it handles deviations from sphericity better. See also [the thread here](https://github.com/singmann/afex/issues/45), with a discussion between the authors of the emmeans and afex packages. 

> A caveat regarding the use of emmeans concerns the assumption of sphericity for ANOVAs including within-subjects/repeated-measures factors (with more than two levels). The current default for follow-up tests uses a univariate model (model = "univariate" in the call to emmeans), which does not adequately control for violations of sphericity. This may result in anti-conservative tests and contrasts somewhat with the default ANOVA table which reports results based on the Greenhousse-Geisser correction. An alternative is to use a multivariate model (model = "multivariate" in the call to emmeans) which should handle violations of sphericity better. The default will likely change to multivariate tests in one of the next versions of the package.

While we have added this option for a while now, I think it's best to make this the default option. I tweaked the unit tests such that those still use the univariate model, although I could also update them such that they use the multivariate tests, but then the results themselves need to be updated. 

Fix https://github.com/jasp-stats/jasp-issues/issues/1221
Fix https://github.com/jasp-stats/jasp-issues/issues/1642

### CODE REVIEW

**Comment by vandenman** [comment]
The reason for the change in default makes sense. That being said,

> although I could also update them such that they use the multivariate tests, but then the results themselves need to be updated.

Please add (at least) one new test with `options$multivariateModelFollowup <- TRUE` :slightly_smiling_face:

**Comment by JohnnyDoorn** [comment]
@vandenman 
Note on the changed unit test:
- The Field results for follow-up tests did not match the actual results in the book, but now they do (they are based on the unpooled SE's now, but now I also still included the results based on the pooled SE's) 
- Updates to the CI's of Cohen's d, since now these also are affected by whether the pooled error term is used
- I still had some errors in the ordinal restrictions (not sure why), and with the bootstrapped marginal means (which are not in Field), but unsure whether this has to do with differences in rng - curious what the github unit tests look like

**Comment by vandenman** [comment]
There are some unit test failures, for example,

```r
Failure ('test-anovarepeatedmeasures.R:1107:3'): Ordinal restrictions: Between factor marginal means table results match
The `test` argument provided to `expect_equal_tables()` is empty. Likely reason: the last run of jaspTools exited with a fatalError:

This analysis terminated unexpectedly.   Error in length(options[['restrictedMarginalMeanTerms']]) = 0 || options[['restrictedMarginalMeanTerms']] = : 'length = 2' in coercion to 'logical(1)'  
```

are these unrelated? If so, it would probably be good to fix these in a separate PR (I can take a look at that).

**Comment by JohnnyDoorn** [comment]
Curious to see if the marginal means for RM ANOVA are now fixed (hopefully for all, but maybe only for mac?), since it passes locally. 
Restricted analyses now run, but still has some issues for an(c)ova (also in simple main effects?!) but will look into those later.

**Comment by JohnnyDoorn** [comment]
@vandenman I ended up removing all gorica fixes, will put them in a separate PR. For now the unit tests are only failing on some marginal means things.. shall we merge this?

**Review by vandenman — APPROVED** [review]

**Pull request merged**
