### PR TITLE
Reduce code duplication in QML forms

### PR DESCRIPTION
**Pull request by Kucharssim**
A refactor of the QML forms. This will help with renaming options for the syntax mode. This PR **does not** rename any options and does not change any of the R code functionality.

### CODE REVIEW

**Comment by vandenman** [comment]
Great idea!

I haven't looked at this yet in detail, but perhaps @boutinb can tell whether it makes sense to also adjust (some of) the translation files? To avoid that all strings need to be translated again.

**Comment by vandenman** [comment]
I found two differences, the rest looks identical to me

| Analysis | 16.3 | This PR |
|----------|------|---------|
| RM-ANOVA | image | image |
 | ANCOVA | image | image |

**Review by vandenman — APPROVED** [review]
If @boutinb has no suggestions for translations then this can be merged.

**Comment by JohnnyDoorn** [comment]
@Kucharssim I think I get an error because of this PR - it seems that one effect size was not renamed properly in https://github.com/jasp-stats/jaspAnova/blame/master/inst/qml/common/classical/Display.qml 
On line 41 it should be effectSizeGenEtaGeneral instead of effectSizePartialEtaGeneral, because else you get this error (only when "Estimes of effect size" is ticked):
image

**Pull request merged**
