### PR TITLE
Limit when Friedman test can be conducted

### PR DESCRIPTION
**Pull request by JohnnyDoorn**
Add an additional check for "unreplicated block design" which is a requirement of the Friedman test.

### CODE REVIEW

**Comment by JohnnyDoorn** [comment]
@Kucharssim @vandenman I'm still getting failing unit tests on the ANOVA.. any idea why? Still get these errors in unchanged analyses: `Error: Error in .subset2(x, i, exact = exact) : subscript out of bounds`

**Comment by Kucharssim** [comment]
> Still get these errors in unchanged analyses: Error: Error in .subset2(x, i, exact = exact) : subscript out of bounds

I noticed this error message before, but it never resulted in failing unit tests. I'll check what's going on

**Comment by JohnnyDoorn** [comment]
@boutinb yes, but I will first fix the failing unit test (for very long time i thought it had a different cause, but now i see why they fail)

**Comment by JohnnyDoorn** [comment]
@boutinb @Kucharssim unit tests have passed, would be very great to include this still for the next release

**Review by Kucharssim — APPROVED** [review]

**Pull request merged**
