### PR TITLE
Bayesian RM-ANOVA: add warning message for older versions about model specification

### PR DESCRIPTION
**Pull request by vandenman**
Part of https://github.com/jasp-stats/INTERNAL-jasp/issues/1829

image

requires https://github.com/jasp-stats/jasp-desktop/commit/3a1976ef25b19be3359df29d886225882586d586

### CODE REVIEW

**Comment by Kucharssim** [comment]
Don't you want to add a reference to a preprint/article?

**Comment by vandenman** [comment]
yes, but there is no preprint yet :stuck_out_tongue:  If that happens before the release I'll add it, but @EJWagenmakers probably wants to take another look at the manuscript first.

**Comment by vandenman** [comment]
If the preprint is not there in time, I could also reference the data library example in https://github.com/jasp-stats/jasp-desktop/pull/4770?

**Comment by Kucharssim** [comment]
> If the preprint is not there in time, I could also reference the data library example in https://github.com/jasp-stats/jasp-desktop/pull/4770? That is the same data set that we use in the manuscript.

Yeah that sounds good!

> yes, but there is no preprint yet 

Ok, did not know that! :)

**Comment by vandenman** [comment]
@Kucharssim is this ok to merge?

**Review by Kucharssim — APPROVED** [review]
Yes, it's fine

**Pull request merged**
