### PR TITLE
Rename standard posthoc test to standard (LSD) and footnote for Dunn's test

### PR DESCRIPTION
**Pull request by JTPetter**
As requested by EJ: Someone asked to verify that the standard option for the post hoc test uses Fisher's LSD method. This was not clear from the interface/helpfile

Do I also need to change this in the Dutch helpfiles? Or are they generated automatically?

Fixes https://github.com/jasp-stats/jasp-issues/issues/1123

### CODE REVIEW

**Review by JohnnyDoorn — APPROVED** [review]

**Comment by JohnnyDoorn** [comment]
> Do I also need to change this in the Dutch helpfiles? Or are they generated automatically?

I think Weblate will automatically pick up the change, and suggest is for the next round of translations (thoughI think it will be the same in all languages)

**Comment by Kucharssim** [comment]
The help files are currently not translated in Weblate, so changes need to be done manually...

**Comment by JTPetter** [comment]
Okay, I have added it to the Dutch help files

**Comment by JTPetter** [comment]
... and the container titles

**Comment by Kucharssim** [comment]
can you fix the conflicts?

**Comment by JTPetter** [comment]
@Kucharssim I completely missed this! I have rebased everything now...

**Comment by JTPetter** [comment]
Rebased again and also fixes https://github.com/jasp-stats/jasp-issues/issues/1123 now

**Comment by JTPetter** [comment]
@Kucharssim could you review/merge please?

**Comment by tomtomme** [comment]
Sorry for the late intervention... but shouldn't the analysis GUI
image
also be renamed to "standard (LSD)" or even "Fishers LSD" - since the term "standard" does not mean or explain anything and currently "Fisher" is not even mentioned in the help file.

**Pull request merged**
