### PR TITLE
make summarySE and summarySEwithin with the .BANOVA names as arguments

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/jaspTTests/issues/9 (Part 1)

- move `summarySE` and `summarySEwithin` to commonAnovaBayesian.R
- export these functions
- add for both function `dependentName = .BANOVAdependentName` and `subjectName = .BANOVAsubjectName` as default arguments.

this only works when checking out https://github.com/jasp-stats/jaspTTests/pull/19 simultaneously.

### CODE REVIEW

**Comment by vandenman** [comment]
ah, that is what you wanted to avoid... In principle, R can handle that but I'd prefer not to make dependencies circular

**Comment by vandenman** [comment]
we should construct a hierarchy then of which packages are allowed to import from each other (e.g., jaspAnova may never import from jaspTTest)

**Comment by vandenman** [comment]
but then I'll just move the functions to jaspTTest and have jaspAnova import these

**Comment by TimKDJ** [comment]
> but then I'll just move the functions to jaspTTest and have jaspAnova import these

Sounds good

**Comment by vandenman** [comment]
@TimKDJ I think this is ready for another review

**Review by TimKDJ — APPROVED** [review]

**Pull request merged**
